---
apiVersion: v1
kind: Deployment
metadata:
  name: stock_api
  namespace: egs6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock_api
  template:
    metadata:
      labels:
        app: stock_api
    spec:
      containers:
        - name: stock_api
          image: registry.deti:5000/mysteryshirt/stock_api:1010
          ports:
            - containerPort: 8080
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: stock_secrets
                  key: db_root_password
            - name: db_name
              value: api
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: stock_api
  namespace: egs6
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: stock_api