version: '3.8'
services:
    db:
        image: db:test
        hostname: stocks_db
        build:
            context: .
            dockerfile: Dockerfile.db
        restart: always
        volumes:
            - db_files:/var/lib/mysql
        environment:
            - MARIADB_DATABASE=stock_db
            - MARIADB_USER=egs
            - MARIADB_PASSWORD=egs 
            - MARIADB_ROOT_PASSWORD=root 
        ports:
            - 3306:3306
        
    app:
        image: app:test
        hostname: stocks
        build:
            context: .
            dockerfile: Dockerfile.app
        ports:
            - 8080:8080
volumes:
    db_files: