# Create nginx deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-stocks
  namespace: egs6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-stocks
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-stocks
    spec:
      containers:
        - image: registry.deti:5000/mysteryshirt/nginx-stocks:1010
          name: nginx-stocks
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always

# Create Service for Nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-stocks
  namespace: egs6
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-stocks

#Create Route
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-stocks
  namespace: egs6
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: app-stocks.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-payments
            port: 
              number: 80