---
apiVersion: v1
kind: Deployment
metadata:
  name: authapi-deployment
  namespace: resende
  labels:
    app: authapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authapi
  template:
    metadata:
      labels:
        app: authapi
    spec:
      containers:
        - name: authapi
          image: registry.deti:5000/resende/api-auth:2022061508
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6000
          env:
            - name: db_root_password
              valueFrom:
                secretKeyRef:
                  name: stock_secrets
                  key: db_root_password
            - name: db_name
              value: api

---
apiVersion: v1
kind: Service
metadata:
  name: authapi-service
  namespace: gasalho
spec:
  ports:
  - port: 6000
    protocol: TCP
    targetPort: 5000
  selector:
    app: authapi