apiVersion: v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: mariadb
    type: database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
        type: database
    spec:
      containers:
        - name: mariadb
          image: mariadb
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: stock_secrets
              value: db_root_password
          volumeMounts:
          - name: mariadb-persistent-storage
            mountPath: /var/lib/mariadb
      
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: stock_db
  namespace: resende
  labels:
    app: db
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: stock_db
  selector:
    app: db