# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ProvidersBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, providers_id: int=None, name: str=None, country: str=None, city: str=None, zip: int=None, address: str=None, email: str=None, site: str=None, phone: int=None):  # noqa: E501
        """ProvidersBody - a model defined in Swagger

        :param providers_id: The providers_id of this ProvidersBody.  # noqa: E501
        :type providers_id: int
        :param name: The name of this ProvidersBody.  # noqa: E501
        :type name: str
        :param country: The country of this ProvidersBody.  # noqa: E501
        :type country: str
        :param city: The city of this ProvidersBody.  # noqa: E501
        :type city: str
        :param zip: The zip of this ProvidersBody.  # noqa: E501
        :type zip: int
        :param address: The address of this ProvidersBody.  # noqa: E501
        :type address: str
        :param email: The email of this ProvidersBody.  # noqa: E501
        :type email: str
        :param site: The site of this ProvidersBody.  # noqa: E501
        :type site: str
        :param phone: The phone of this ProvidersBody.  # noqa: E501
        :type phone: int
        """
        self.swagger_types = {
            'providers_id': int,
            'name': str,
            'country': str,
            'city': str,
            'zip': int,
            'address': str,
            'email': str,
            'site': str,
            'phone': int
        }

        self.attribute_map = {
            'providers_id': 'providers_ID',
            'name': 'name',
            'country': 'country',
            'city': 'city',
            'zip': 'ZIP',
            'address': 'address',
            'email': 'email',
            'site': 'site',
            'phone': 'phone'
        }
        self._providers_id = providers_id
        self._name = name
        self._country = country
        self._city = city
        self._zip = zip
        self._address = address
        self._email = email
        self._site = site
        self._phone = phone

    @classmethod
    def from_dict(cls, dikt) -> 'ProvidersBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The providers_body of this ProvidersBody.  # noqa: E501
        :rtype: ProvidersBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def providers_id(self) -> int:
        """Gets the providers_id of this ProvidersBody.


        :return: The providers_id of this ProvidersBody.
        :rtype: int
        """
        return self._providers_id

    @providers_id.setter
    def providers_id(self, providers_id: int):
        """Sets the providers_id of this ProvidersBody.


        :param providers_id: The providers_id of this ProvidersBody.
        :type providers_id: int
        """

        self._providers_id = providers_id

    @property
    def name(self) -> str:
        """Gets the name of this ProvidersBody.


        :return: The name of this ProvidersBody.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProvidersBody.


        :param name: The name of this ProvidersBody.
        :type name: str
        """

        self._name = name

    @property
    def country(self) -> str:
        """Gets the country of this ProvidersBody.


        :return: The country of this ProvidersBody.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country: str):
        """Sets the country of this ProvidersBody.


        :param country: The country of this ProvidersBody.
        :type country: str
        """

        self._country = country

    @property
    def city(self) -> str:
        """Gets the city of this ProvidersBody.


        :return: The city of this ProvidersBody.
        :rtype: str
        """
        return self._city

    @city.setter
    def city(self, city: str):
        """Sets the city of this ProvidersBody.


        :param city: The city of this ProvidersBody.
        :type city: str
        """

        self._city = city

    @property
    def zip(self) -> int:
        """Gets the zip of this ProvidersBody.


        :return: The zip of this ProvidersBody.
        :rtype: int
        """
        return self._zip

    @zip.setter
    def zip(self, zip: int):
        """Sets the zip of this ProvidersBody.


        :param zip: The zip of this ProvidersBody.
        :type zip: int
        """

        self._zip = zip

    @property
    def address(self) -> str:
        """Gets the address of this ProvidersBody.


        :return: The address of this ProvidersBody.
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address: str):
        """Sets the address of this ProvidersBody.


        :param address: The address of this ProvidersBody.
        :type address: str
        """

        self._address = address

    @property
    def email(self) -> str:
        """Gets the email of this ProvidersBody.


        :return: The email of this ProvidersBody.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this ProvidersBody.


        :param email: The email of this ProvidersBody.
        :type email: str
        """

        self._email = email

    @property
    def site(self) -> str:
        """Gets the site of this ProvidersBody.


        :return: The site of this ProvidersBody.
        :rtype: str
        """
        return self._site

    @site.setter
    def site(self, site: str):
        """Sets the site of this ProvidersBody.


        :param site: The site of this ProvidersBody.
        :type site: str
        """

        self._site = site

    @property
    def phone(self) -> int:
        """Gets the phone of this ProvidersBody.


        :return: The phone of this ProvidersBody.
        :rtype: int
        """
        return self._phone

    @phone.setter
    def phone(self, phone: int):
        """Sets the phone of this ProvidersBody.


        :param phone: The phone of this ProvidersBody.
        :type phone: int
        """

        self._phone = phone
