---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-payments
  namespace: egs6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-payments
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-payments
    spec:
      containers:
        - name: nginx-payments
          image: registry.deti:5000/mysteryshirt/nginx-payments:1014
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-payments
  namespace: egs6
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-payments

# Configure Traefik
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-k3s
  namespace: egs6
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: payments-api.egs
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-payments
            port: 
              number: 80