version: '3.8'
services:
  db:
    image: payments_db:test
    hostname: payments_db
    build:
      context: .
      dockerfile: dockerfile.db
    restart: always
    volumes:
      - db_files:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=payments_db
      - MARIADB_USER=egs
      - MARIADB_PASSWORD=egs
      - MARIADB_ROOT_PASSWORD=root
    ports:
      - 3306:3306

  app:
    image: app:test
    hostname: payments_app
    build:
      context: .
      dockerfile: dockerfile.app
    ports:
      - 9021:9021

volumes:
  db_files:

