---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-shirts
  namespace: egs6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-shirts
  template:
    metadata:
      labels:
        app: app-shirts
    spec:
      containers:
      - name: app-shirts
        image: registry.deti:5000/mysteryshirt/app:1013
        ports:
          - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: app-shirts
  namespace: egs6
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    app: app-shirts
