version: '3.8'
services:
    db:
        image: db:test
        hostname: auth_db
        build:
            context: .
            dockerfile: Dockerfile.db
        restart: always
        volumes:
            - db_files:/var/lib/mysql
        environment:
            - MARIADB_DATABASE=auth_db
            - MARIADB_USER=egs
            - MARIADB_PASSWORD=egs 
            - MARIADB_ROOT_PASSWORD=root 
        ports:
            - 3306:3306
        
    app:
        image: app:test
        hostname: auth_app
        build:
            context: .
            dockerfile: Dockerfile.app
        ports:
            - 80:80
volumes:
    db_files: